apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - image: 24points-ui
        name: ui
        imagePullPolicy: Never
        ports:
        - containerPort: 8190
          name: ui
